GET http://localhost:3000/inventory

###

GET http://localhost:3000/inventory/6389aa4fa3554571be9ab29e

###

POST http://localhost:3000/inventory
Content-Type: application/json

{
    "text": "Men's Blue Polo",
    "description": "A men's blue polo shirt",
    "price": "$12.00",
    "image": "https://m.media-amazon.com/images/I/719uG0-FGCS._AC_UL1500_.jpg",
    "quantity": 1
}

###

DELETE http://localhost:3000/inventory/6389adf616d8df7242d152c5

###

PATCH http://localhost:3000/inventory/6389aec0acda261ddf1dd43e
Content-Type: application/json

{
    "price": "$20.00"
}